- name: Build with Astro
  env:
    GH_CONTRIB_TOKEN: ${{ secrets.GH_CONTRIB_TOKEN }}
  run: |
    ${{ steps.detect-package-manager.outputs.runner }} astro build \
      --site "${{ steps.pages.outputs.origin }}" \
      --base "${{ steps.pages.outputs.base_path }}"